### ISSUE TITLE
missing of 'test_with_shuffle_label.h5 'file

### ISSUE THREAD

**Issue by AkshayKumarEdayilliam** [ICVGIP-Challenge/AudioVisualRetrieval-21#1]
I have cloned repo as it is and downloaded the dataset. But while running evaluate_triplet.py am getting the following error
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = './data/features/test_with_shuffle_label.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Please help to solve the error

**Comment by krantiparida** [comment]
Hi, the error was due to loading the 'test' file instead of 'val'. However, I have updated the evaluate_triplet.py file. It should work fine now.  Can you check now and see if it is working correctly at your end?

**Comment by AkshayKumarEdayilliam** [comment]
Dear sir,
Thank you for the help. It's working fine now. I have gone through both the papers mentioned. so What u are expecting from the contestants? Is it improvement in the performance?

**Comment by krantiparida** [comment]
Yes, the goal is to get maximum improvement.
