### ISSUE TITLE
About wildlife detection

### ISSUE THREAD

**Issue by iscyy** [ICVGIP-Challenge/AudioVisualRetrieval-21#2]
Is anyone responsible for answering questions in this competition? Thank you. There is an issue.
https://github.com/ICVGIP-Challenge/SpeciesDetection-21

**Comment by krantiparida** [comment]
Hi @Him-wen, this repo is for a different task in the challenge. Please post your questions [here](https://github.com/ICVGIP-Challenge/SpeciesDetection-21/issues). Thanks.

**Comment by Him-wen** [comment]
Because the repo did not answer, the question is very urgent, thank you

**Comment by Him-wen** [comment]
@krantiparida
